let code1;
code1 = 7 + 3;
const code2 = 84 / 2 - 2;
const code3 = (78 % 5) + 36;
const message = "The vault has been secured. The combination is:";
const codeA = code1 + "-" + code2 + "-" + code3;
const codeB = `${code1}-${code2}-${code3}`;
console.log(message);
console.log(codeA);
console.log(codeB);
